apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tg0rwaimn-nodejs 
  janus-idp.io/tekton: tg0rwaimn-nodejs
  backstage.io/kubernetes-id: tg0rwaimn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tg0rwaimn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml